site:
  name: AstroWind
  site: 'https://hyunsoo0o0o0.github.io'
  base: '/My-little-landing-page/'
  trailingSlash: true

  googleSiteVerificationId: orcPxI47GSa-cRvY11tUe6iGg2IO_RPvnA1q95iEM3M

# Default SEO metadata
metadata:
  title:
    default: AstroWind
    template: '%s — AstroWind'
  description: "\U0001F680 Suitable for Startups, Small Business, Sass Websites, Professional Portfolios, Marketing Websites, Landing Pages & Blogs."
  robots:
    index: true
    follow: true
  openGraph:
    site_name: AstroWind
    images:
      - url: '~/assets/images/default.png'
        width: 1200
        height: 628
    type: website
  twitter:
    handle: '@arthelokyo'
    site: '@arthelokyo'
    cardType: summary_large_image

i18n:
  defaultLocale: en
  locales:
    en:
      name: English
      direction: ltr
    ko:
      name: 한국어
      direction: ltr

apps:
  blog:
    isEnabled: false

analytics:
  vendors:
    googleAnalytics:
      id: null # or "G-XXXXXXXXXX"

ui:
  theme: 'system' # Values: "system" | "light" | "dark" | "light:only" | "dark:only"
